#name: HCX Secure Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # ONLY strategy + code updates (NO PRIVATE KEYS)
      - name: Compile Contracts
        run: npx hardhat compile

      - name: Deploy BuildBear (test only)
        uses: BuildBearLabs/buildbear_x_action@v1.7.0
        with:
          network: |
            [{ "chainId": 1 }]
          deploy-command: "bash deploy-buildbear.sh"
          buildbear-api-key: ${{ secrets.BUILDBEAR_API_KEY }}
          environment-id: "decent-greengoblin-1ff20e78"
